### ISSUE TITLE
Unknown subcommand XX for command 0xXX

### ISSUE THREAD

**Issue by Bobavince** [fgsect/scat#1]
Hi ! 
I'm trying to run this project, after some try-and-fail I'm getting to something that does work, but only for few seconds/dozen of seconds.

### Setup : 
* Samsung Galaxy S6 Edge Plus (Samsung SM-G928F)
* Seems to be Exynos 5433 + Shannon 333 

### Command : 
* sudo ./scat.py -t sec -m e333 -u -a 001:010 -i 2

### Error :

```
(hexa print, correct, able to get it from Wireshark)
-------- end --------
Something wrong
64 00 00 00 00 fb ff 61 64 00 00 00 00 67 75 61	d......ad....gua
64 67 75 61 64 67 75 61 64 67 75 61 64 67 7e   	dguadguadguadg~
-------- end --------
Unknown subcommand 00 for command 0x21
Unknown subcommand 02 for command 0x21
Unknown subcommand 00 for command 0x21
Unknown subcommand 02 for command 0x21
(...continously, 2 per second, no more correct hexa print)
```
### Tests :
* Reboot the smartphone
* Reconnect the smartphone
* Reboot the script (Even on first launch of the script and the smartphone, it happens.)

That's not a big deal, and maybe it's coming from my setup. I will perform further tests, but if you know "in one blink" why it doesn't work ... I would be glad to have your feedback. :)

Thanks, 
See you !

**Comment by peremen** [comment]
Hi. First of all, I also tested on the same model, and some of errors are also present in my environment.

```
64 00 00 00 00 fb ff 61 64 00 00 00 00 67 75 61	d......ad....gua
64 67 75 61 64 67 75 61 64 67 75 61 64 67 7e   	dguadguadguadg~
```

That is expected, unfortunately I don't know what that text ("guad") means.

```
Unknown subcommand 00 for command 0x21
Unknown subcommand 02 for command 0x21
(...continously, 2 per second, no more correct hexa print)
```

That is also expected, as I won't be able to dissect all diagnostic messages. Do you still get RRC/NAS messages? If it is, then it is just a matter of removing debug output. If it is not, then something is wrong.

**Comment by Bobavince** [comment]
Hi ! 
Thanks for your answer.

Okay. So it seems - by your side checks - that it's a model-related problem. 
Indeed, I'm still catching messages with Wireshark. (GMSMTAP, RRC, no NAS).
I understand that it cannot dissect all diagnostic message, but at some point, it does not dissect any more diagnostic message (at least in the console). That's why I was disturbed.

By looking carefully at the standard output, it seems even first messages are not parsed correctly. It seems nonetheless that Wireshark is still able to decode them.
If I encounter issues with Wireshark packet analysis, I get back to you :) 

For reference : 
```
 USB device at address 001:019
  CONFIGURATION 1: 96 mA ===================================
   bLength              :    0x9 (9 bytes)
 (...)
       bInterval        :    0x0
-------- initialize diag --------
-------- start diag --------
Invalid packet structure
7f a3 07 00 a0 07 37 00 a1 05 10 1d 1b 00 00 09	......7.........
00 00 88 95 0f 42 00 00 01 02 00 00 00 09 01 00	.....B..........
80 97                                          	..
-------- end --------
Something wrong
0f 42 00 00 01 04 00 00 00 09 01 00 68 bc 0f 42	.B..........h..B
(...)
00 00 03 00 00 00 51 30 00 00 00 00 00 00 00 00	......Q0........
00 00 7e                                       	..~
-------- end --------
Invalid packet structure
7f b6 07 00 b3 07 b0 00 a1 05 10 cb 75 08 00 0f	............u...
(...)
00 01 a0 19 71 40 7e                           	....q@~
-------- end --------
Invalid packet structure
7f a0 07 00 9d 07 02 01 a1 06 01 9c 5c 09 00 00	............\...
(...)
00 00 00 00 00 00 00 00 00 00 00 00 00 7e      	.............~
-------- end --------
Invalid packet structure
7f 43 01 00 40 01 39 01 a1 06 01 5d 59 0e 00 01	.C..@.9....]Y...
(...)
34 1c 00 00 01 00 00 00 01                     	4........
-------- end --------
Something wrong
00 00 00 01 00 00 00 00 00 00 00 fb ff 00 00 00	................
(...)
00 00 00 28 50 c7 43 28 50 c7 43 2c 0b 00 00 7e	...(P.C(P.C,...~
-------- end --------
Unknown subcommand 00 for command 0x21
Unknown subcommand 02 for command 0x21
(...)
Unknown subcommand 00 for command 0x21
Unknown subcommand 02 for command 0x21
...
(ONLY these "unkown subcommand" lines are printed)
```

Thanks, again !

**Comment by Bobavince** [comment]
Hi !
Okay, all good. Everything was question of parameters and a working connection.
So there is still the "Unkown subcommand ..." but Wireshark capture is all good (LTE RRC DL_SCH, GSMTAP/NAS-EPS ,LTE RRC UL_DCCH/NAS-EPS, S1AP/NAS-EPS, SCTP ...)

Thanks a lot for your help :+1:
