### ISSUE TITLE
No LTE MAC PDUs decoded in wireshark after installing wireshark plugin

### ISSUE THREAD

**Issue by mohanrajpExploring** [fgsect/scat#102]
**[ Issue ]**

No LTE MAC PDUs were decoded after installing the scat.lua file included in [scat/wireshark](https://github.com/fgsect/scat/tree/2903b25c20c68018c5568b0aa09e637c8bbcf64d/wireshark) folder.

**[ Description ]**

From the below snip please observe that enabled protocols in analyze tab show mac-lte-framed is enabled.
But there is no MAC PDU found in the .pcap file.

This is in continuation with [#101](https://github.com/fgsect/scat/issues/101#issue-2298281302)

snippet:
![image](https://github.com/fgsect/scat/assets/168116222/512601e2-eb07-499f-934f-e6dc30209873)

---
Thanks,

Please let me know if I need to provide more details.

**Comment by peremen** [comment]
Please do not use the issue tracker as your personal Q&A space, when you're not sure whether this is a SCAT bug. You have been warned.

SCAT will send different log mask when MAC layer is enabled to enable LTE MAC PDU log items. In the #101 you used the QMDL file, I don't know how you've generated that file. If the MAC log item is not included in the QMDL file then there will be no LTE MAC packets. If the packet's version is not supported then there will be error message, but if there is no packet from the first place then nothing will appear at all.
