### ISSUE TITLE
Packaging dependency is missing on new python environments

### ISSUE THREAD

**Issue by jnunez101** [fgsect/scat#105]
**SUMMARY**
SCAT installed through pip gives a module not found error. Specifically 'packaging' is missing. 

**STEPS TO REPRODUCE**
1. Install SCAT in a new python environment (I am making docker containers)
2. Run SCAT using the qualcomm parser

**EXPECTED and ACTUAL RESULT**
Traceback (most recent call last):
  File "/usr/local/bin/scat", line 5, in <module>
    from scat.main import scat_main
  File "/usr/local/lib/python3.12/site-packages/scat/main.py", line 6, in <module>
    import scat.parsers
  File "/usr/local/lib/python3.12/site-packages/scat/parsers/__init__.py", line 3, in <module>
    from scat.parsers.qualcomm.qualcommparser import QualcommParser
  File "/usr/local/lib/python3.12/site-packages/scat/parsers/qualcomm/qualcommparser.py", line 9, in <module>
    from scat.parsers.qualcomm.diaggsmlogparser import DiagGsmLogParser
  File "/usr/local/lib/python3.12/site-packages/scat/parsers/qualcomm/diaggsmlogparser.py", line 9, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**ENVIRONMENT**
 - OS: Arch Linux running an Alpine Docker container
 - SCAT version: Master
 - Python version: 3.12.3
 - Cellular device: Not needed to see error but Quectel RM502
 - Baseband type: Qualcomm
 - DIAG method: serial

**ADDITIONAL INFORMATION**
I added packaging>=24.0 to the dependencies on pyproject.toml and that fixed the issue.

**Comment by M0hanrajp** [comment]
@peremen 

I also encountered similar error `ModuleNotFoundError: No module named 'packaging'` while installing scat.


Can we make the following changes to [scat/pyproject.toml](https://github.com/fgsect/scat/tree/master/pyproject.toml) ?
```toml
requires-python = ">=3.7"
dependencies = [
    "pyusb>=1.0.2",
    "pyserial>=3.3",
    "bitstring>=3.1.7",
    "packaging>=20.0"  # Added the packaging module here
]
```
Additional info: [packaging](https://pypi.org/project/packaging/)

---

**Comment by peremen** [comment]
After checking [repology](https://repology.org/project/python:packaging/versions) I added an explicit dependency in the pyproject.toml file, and this should fix the issue.

@M0hanrajp you don't have to mention me in every issues.
