### ISSUE TITLE
QMDL parsed in a wrong way

### ISSUE THREAD

**Issue by HandyMenny** [fgsect/scat#11]
In the master branch QMDL are parsed in this strange way: ![immagine](https://user-images.githubusercontent.com/3463028/57628972-4173ce80-759b-11e9-8784-dc14b23f37a4.png) 

Here how the same qmdl was parsed before commit https://github.com/fgsect/scat/commit/c637d055ce6b634aa6e6b9e2d2699752bdd465eb : 
![immagine](https://user-images.githubusercontent.com/3463028/57629404-0a51ed00-759c-11e9-842c-a1f803a239df.png)

**Comment by peremen** [comment]
This is an intended feature. Log messages could be also sent via Qualcomm DIAG messages, and the commit c637d05 contains the function ```parse_diag_ext_msg``` which parses that message. They have separate GSMTAP header from the rest of signaling messages (payload type is ```0x10 OSMOCORE_LOG```) so you can filter by ```!(gsmtap.type == 0x10)```.

**Comment by HandyMenny** [comment]
Okay, I'm sorry. I didn't notice that. In my case I can filter with (gsmtap.type != 0x10)
