### ISSUE TITLE
5G SA SDM(Exynos) to PCAP

### ISSUE THREAD

**Issue by iman432** [fgsect/scat#113]
Hi,

I converted a sdm log to pcap. LTE messages are normal but NR messages aren't show up in wireshark. can scat convert 5G SA to pcap?

**Comment by peremen** [comment]
SDM 5G support is currently not available to public. Please contact me in private for more details.

**Comment by iman432** [comment]
> SDM 5G support is currently not available to public. Please contact me in private for more details.

I sent email to you one month ago, can you please check.

**Comment by peremen** [comment]
I didn't received the mail from you. Could you please resend it?
