### ISSUE TITLE
parse_wcdma_search_cell_reselection_v2:  Number of 2G cells greater than 0

### ISSUE THREAD

**Issue by HandyMenny** [fgsect/scat#14]
2019-07-15 21:23:33,923 scat.qualcommparser (parse_wcdma_search_cell_reselection_v2) WARNING: Hexdump: 
84 04 00 00 00 00 00 93 0b 49 00 cf 00 80 dc 00	.........I......
80 00 00 00 00 00 00 93 0b 99 01 d5 c0 ff e0 e0	................
ff 02 00 00 00 00 00 ea 0b 99 01 da c5 ff ec ec	................
ff 02 00 00 00 00 00 ea 0b 49 00 da c5 ff ec ec	.........I......
ff 01 00 00 21 00 03 67 00 05 05 ce c7 ff 02 00	....!..g........
00 00 00 00 75 00 02 06 c6 bf ff 02 00 00 00 00	....u...........
00 6b 00 05 05 c6 bf ff 02 00 00 00 00 00 68 00	.k............h.
05 06 bd b6 ff 02 00 00 00 00 00               	...........

**Comment by peremen** [comment]
Because nearly all of my devices I have showed zero 2G cells on 3G neighbor cell search, as shown in that warning message of `parse_wcdma_search_cell_reselection_v2`. Therefore I left that as an error condition. I will take a look on it.

**Comment by peremen** [comment]
Okay, quite a lot of thing had been changed in the current master. Could you please test again?

**Comment by HandyMenny** [comment]
yes sure, in the next few days I will check if everything works well

**Comment by HandyMenny** [comment]
It returns this error:
Traceback (most recent call last):
  File "scat.py", line 152, in <module>
    current_parser.read_dump()
  File "parsers/qualcomm/qualcommparser.py", line 255, in read_dump
    self.parse_dlf()
  File "parsers/qualcomm/qualcommparser.py", line 240, in parse_dlf
    self.parse_diag(pkt, hdlc_encoded = False)
  File "parsers/qualcomm/qualcommparser.py", line 171, in parse_diag
    self.parse_diag_log(pkt, radio_id)
  File "parsers/qualcomm/qualcommparser.py", line 274, in parse_diag_log
    self.process[xdm_hdr[1]](pkt_ts, pkt_body, radio_id)
  File "parsers/qualcomm/diagltelogparser.py", line 44, in <lambda>
    0xB0C0: lambda x, y, z: self.parse_lte_rrc(x, y, z), # LTE RRC OTA Message
  File "parsers/qualcomm/diagltelogparser.py", line 898, in parse_lte_rrc
    self.lte_last_earfcn_dl[radio_id] = earfcn
AttributeError: 'DiagLteLogParser' object has no attribute 'lte_last_earfcn_dl'

**Comment by HandyMenny** [comment]
I fixed that issue, see #15, now it works well:  Radio 0: 4 3G cells, 4 2G cells
Radio 0: 3G Cell 0: UARFCN 2963, PSC  73, RSCP -70, Ec/Io -18.00
Radio 0: 3G Cell 1: UARFCN 2963, PSC 409, RSCP -64, Ec/Io -16.00
Radio 0: 3G Cell 2: UARFCN 3050, PSC 409, RSCP -59, Ec/Io -10.00
Radio 0: 3G Cell 3: UARFCN 3050, PSC  73, RSCP -59, Ec/Io -10.00
Radio 0: 2G Cell 0: ARFCN 103, RSSI -50.00, Rank -57
Radio 0: 2G Cell 1: ARFCN 117, RSSI -58.00, Rank -65
Radio 0: 2G Cell 2: ARFCN 107, RSSI -58.00, Rank -65
Radio 0: 2G Cell 3: ARFCN 104, RSSI -67.00, Rank -74

**Comment by peremen** [comment]
> It returns this error:
> Traceback (most recent call last):
> File "scat.py", line 152, in
> current_parser.read_dump()
> File "parsers/qualcomm/qualcommparser.py", line 255, in read_dump
> self.parse_dlf()
> File "parsers/qualcomm/qualcommparser.py", line 240, in parse_dlf
> self.parse_diag(pkt, hdlc_encoded = False)
> File "parsers/qualcomm/qualcommparser.py", line 171, in parse_diag
> self.parse_diag_log(pkt, radio_id)
> File "parsers/qualcomm/qualcommparser.py", line 274, in parse_diag_log
> self.process[xdm_hdr[1]](pkt_ts, pkt_body, radio_id)
> File "parsers/qualcomm/diagltelogparser.py", line 44, in
> 0xB0C0: lambda x, y, z: self.parse_lte_rrc(x, y, z), # LTE RRC OTA Message
> File "parsers/qualcomm/diagltelogparser.py", line 898, in parse_lte_rrc
> self.lte_last_earfcn_dl[radio_id] = earfcn
> AttributeError: 'DiagLteLogParser' object has no attribute 'lte_last_earfcn_dl'

Oops, that looks like the error was caused during the refactoring. I mainly use QMDL, so the dlf code path might need some love. I will also take care of that too.
