### ISSUE TITLE
Running on nexus 5 smartphone

### ISSUE THREAD

**Issue by mohammad-shekarifard** [fgsect/scat#16]
Hi, according to the README document i used the SCAT(master brunch) tool for nexus 5 smartphone, but i do not understand why i am getting this results from wireshark? what should i do to wireshark to show the GSMTAP header? my wireshark version is 2.6.8

![Screenshot from 2019-08-11 19-18-18](https://user-images.githubusercontent.com/36436603/62942178-0167f600-bded-11e9-80b5-a5208b4644bd.png)

**Comment by peremen** [comment]
Uhm, this seems not good. Assuming that you've rooted the phone and changed the USB configuration, try with display filter "gsmtap" or "udp.port == 4729".

**Comment by mohammad-shekarifard** [comment]
Hi, Thanks for quick answer. I applied "gsmtap" and "udp.port == 4729" filters  on wireshark but nothing shows up. in the phone what USB configuration mood should i select? (charching or MTP or PTP or RNDIS or MIDI)

**Comment by peremen** [comment]
Please check the README for what command is required for Nexus devices. Note that you don't need to change the USB connection mode after entering the command via adb.
