### ISSUE TITLE
Samsung S6 SM-G920F

### ISSUE THREAD

**Issue by manchili** [fgsect/scat#19]
Greetings!
I tried this on Samsung S6 SM-G920F which is rooted.  I am receiving the packets on wireshark however I have the following errors on the console.  Can you please tell me how to eliminate them or can they be ignored or what is root cause of it ?

Thank you very much in advance. If you need any further information, please feel free to bother.

*lsusb output is as follows*
```Bus 003 Device 006: ID 04e8:685d Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II] (Download mode)```

*./scat.py -t sec -m e333 -u -a 003:006 -i 2*
```Trying USB device at address 003:006
  CONFIGURATION 1: 96 mA ===================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x79 (121 bytes)
   bNumInterfaces       :    0x4
   bConfigurationValue  :    0x1
   iConfiguration       :    0x
...
...
    INTERFACE 3: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x3
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0x42
     bInterfaceProtocol :    0x1
     iInterface         :    0x0 
      ENDPOINT 0x84: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x84 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x3: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x3 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
2019-09-25 10:45:13,476 scat.samsungparser (stop_diag) INFO: Stopping diag
2019-09-25 10:45:13,479 scat.samsungparser (init_diag) INFO: Initialize diag
2019-09-25 10:45:13,484 scat.samsungparser (run_diag) INFO: Starting diag
2019-09-25 10:45:13,638 scat.samsungparser (parse_diag_log_e333) WARNING: Invalid packet structure
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./scat.py", line 158, in <module>
    current_parser.run_diag()
  File "/Downloads/scat/parsers/samsung/samsungparser.py", line 147, in run_diag
    self.logger.warning(logging.WARNING, 'Something wrong')
Message: 30
Arguments: ('Something wrong',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./scat.py", line 158, in <module>
    current_parser.run_diag()
```

**Comment by manchili** [comment]
![SCTA-Wireshark-SamsungS6](https://user-images.githubusercontent.com/27067446/65661484-106bd600-e032-11e9-9f07-17ff9f28973b.jpg)

I am here attaching the screenshot of Wireshark captured packets filtered by *gsmtap*.  Please let me know the what should I do for the above errors ? 

Thank you in advance.

**Comment by manchili** [comment]
@peremen 
Can you please help ?

**Comment by peremen** [comment]
For the issue in my first comment, this is my mistake. The code should not produce the error as in the log in that condition, but the root cause of triggering that error is still unknown to me (hence the message). I can make a quick fix.

For the second issue, do you mean hiding ICMP packets? That is mostly harmless, could be filtered by adding "not icmp".

**Comment by manchili** [comment]
Thank you very much for quick reply. I am impressed with your work. I got to know this link just two days ago from awesome-telecom.

First one:  Thank you for clarification. Log tells *'Something wrong'*  but I can capture traffic, so therefore it confused me if I did something wrong in the arguments.  For me still sometimes not clear what is the exact value to be passed after ```-i```.  Is there a way to find ?

Second one is not issue, i had shared the screenshot because to tell that I see traffic but error messages on console by scta.py 
script 
Yes, I did filter as follows. It is very clear view now.
 ```udp.dstport == 4729 or udp.srcport == 4729 or udp.dstport == 47290 or udp.srcport == 47290 and !icmp```
I see lot of UDP traffic (User plane traffic), Is there a way to decode that ?

![SCTA-Wireshark-SamsungS6-Filters](https://user-images.githubusercontent.com/27067446/65679855-3905c700-e056-11e9-8b9a-1732e326267c.jpg)

**Comment by peremen** [comment]
> First one: Thank you for clarification. Log tells _'Something wrong'_ but I can capture traffic, so therefore it confused me if I did something wrong in the arguments. For me still sometimes not clear what is the exact value to be passed after `-i`. Is there a way to find ?

At least the error message should be less confusing in this moment. Regarding the interface number specified by `-i`, the same information printed during SCAT startup is available via `lsusb -v` command. You can find Interface Descriptor of the smartphone there, and interface having bInterfaceClass == 0xff will likely be the number which should be passed into `-i`.

> Second one is not issue, i had shared the screenshot because to tell that I see traffic but error messages on console by scta.py
> I see lot of UDP traffic (User plane traffic), Is there a way to decode that ?

These are just an IP packet wrapped inside UDP packet. Right click on it and decode UDP port 47290 as IP, then you can see the data packet.

**Comment by manchili** [comment]
Thank you very much. 
All clear.
