### ISSUE TITLE
Samsung devices, metadata information like EARFCN is missing

### ISSUE THREAD

**Issue by kapilshra** [fgsect/scat#25]
HI Team,

Thanks alot for great tool. I'm trying to use the tool for my project in automating Radio L2 and L3 messages capture. I run tool on Samsung S8/S10+.

I am not getting full data from GSMTAP Samsung Galaxy S8 (SM-G950F) and Samsung S10+ Exynos chipset. AFRAN, CELL DATA is missing,

I would really appreciate if you could have a look. Please let me know if you need more information,
[sim5.zip](https://github.com/fgsect/scat/files/4418471/sim5.zip)

Regards
Kapil Sharma

**Comment by peremen** [comment]
I haven't deeply looked into Samsung parser these days, as I don't have access to the recent Samsung devices (S9 and above) at this moment. I will give a try, also #21 will be handled too.

**Comment by peremen** [comment]
Just looked into the attached file, it seems like the log was generated by Qualcomm device. I also have other not-working reports of Samsung devices atm.
