### ISSUE TITLE
scat doesn't work with Samsung Exynos 5G devices

### ISSUE THREAD

**Issue by HandyMenny** [fgsect/scat#27]
The Finnish S10 5G on which we were testing, after the update that enabled 5G in Finland has stopped working with scat. I tried to use my [raw writer](https://github.com/HandyMenny/scat/commit/6a472e26b50ac8bee9f96b13f2979831bb658364) and the output was empty, so I think no diag messages are sent.
The same problem occurs with S20 5G (family) in Finland, UK and Italy. There is a similar problem also with all the S7 and S7 edges that we've tried, I don't know if it's related to this issue, but such a problem never happened with S6, S8, S9, S10 4G, S10e and other (midrange) exynos devices that we've tested.
We tried to disable 5G in the settings but nothing changed.

Moreover 5G devices show two DMs, DM and DM(2CP), in *#0808#, but it's impossible to enable the second one. I guess the second DM is only for qualcomm devices.

There is no error or warning, so I've nothing else to share

**Comment by peremen** [comment]
Hmm, that's interesting. Maybe the entire diagnostic protocol have been changed, so further engineering might be required in this case.

**Comment by HandyMenny** [comment]
No. Even with the official samsung tools sometimes it isn't possible to access the diag of these devices, apparently in some firmwares the diag is disabled or is "busy", this also happens with 4G devices. I forgot to close this issue, in the end it is not a problem of SCAT, but of the devices

**Comment by whitecloudy** [comment]
Could you plz tell me where can I find the 'Official samsung tools' for diag?

**Comment by peremen** [comment]
Update on Samsung devices: Some years ago Samsung made the magic number check of `START DIAG` message more strict, that was the reason why there is no DIAG data from Samsung devices as SCAT simply uses `AAAA` as magic number which is not valid. While the magic number is available on the baseband firmware itself, and possible to be obtained by disassembly, but the problem is I don't want to play a whack-a-mole game on those numbers. This hurts also users too.

I added an option to supply the magic number on `START DIAG` (`--start-magic`), but the number itself I am afraid to tell in the public place.

**Comment by peremen** [comment]
As an alternative, you can use SilentLog hidden application to get the SDM files and can decode using SCAT. Check the information on https://github.com/fgsect/scat/wiki/Baseband-Dumps

**Comment by spicyKo0l** [comment]
Hi Peremen,  Greetings of The Day! Thank you for your support.  I am writing to you regarding Samsung S7 Exynos  8890 as I am unable to see the traffic when trying to capture. I had also seen the comments regarding that you have no solution and you are not clear why it is not working on Samsung S7 but you had given some reference issue#27 where you had given alternatives.
1. START DIAG (--start-magic)  I am not clear where to and what to give.
2.  SDM files, I tried enabling SilentLog but not able to see *.SDM files on the S7.

**Comment by peremen** [comment]
> START DIAG (--start-magic) I am not clear where to and what to give.

Please PM me (see my profile) for the correct value, thanks.

> SDM files, I tried enabling SilentLog but not able to see *.SDM files on the S7.

Samsung SilentLog should store directly to the mass storage of the Android. I don't have and can't test on all possible devices.
