### ISSUE TITLE
Mi Mix 3 5G support

### ISSUE THREAD

**Issue by ravens** [fgsect/scat#28]
Just to inform that the Xiaomi Mi Mix3 5G (Qualcomm, compatible n78 band) is supported by scat, with the following process:
- unlock phone with the official xiaomi feature in the development options, wait 7 days for the unlock to be authorized after initial registration
- TWRP (andromeda) + Magisk root
- adb shell, su, setprop sys.usb.config diag,adb
- python3 scat.py -t "qc" -u -a XXX:XXX -H 127.0.0.1 -i "0" so interface 0 seems the relevant one.

**Comment by bedrankara** [comment]
The interface number (_bInterfaceNumber_) to be passed to **-i** is usually the interface with the **bInterfaceClass** == 255 .

**Comment by peremen** [comment]
Thanks for the report.
