### ISSUE TITLE
Support for LTE ML1 Serving Cell Meas Resp Subpacket v48

### ISSUE THREAD

**Issue by Awaisryk** [fgsect/scat#33]
OS: Ubuntu 20.04
Python version: 3.7.3
Can you please add support for 0xB193 LTE ML1 Serving Cell Meas Resp Subpacket v48?

If you can help me with the packet structure, I can add it to the code myself.
Attached is the log file
[testfile.qmdl.gz](https://github.com/fgsect/scat/files/4755239/testfile.qmdl.gz)
Thanks.

**Comment by peremen** [comment]
Sorry about late response. I will check out soon.

**Comment by Awaisryk** [comment]
Did you get a chance to look into this?

**Comment by peremen** [comment]
I was busy these days. Can take a look on it.

**Comment by Awaisryk** [comment]
Sure. Let me know if you want any additional sample files for testing or stuff.

**Comment by peremen** [comment]
Okay, commit 69e6ba426064efa01b3b371a492123c5c5d5cf30 should contain some preliminary support for this. I think your interest is RSRP/RSRQ/RSSI, but it seems that the subpacket V48 seems to differ from V36/V40 which I have decode access so far. Would it be possible to send me a "decoded" version of any of the packet? I could implement one based on V36/V40 but not sure whether the data is accurate.

**Comment by Awaisryk** [comment]
Unfortunately, I don't have decoded version of v48 packet. I tried to decode it using v40 structure but the values were not correct as you mentioned.

**Comment by Awaisryk** [comment]
Do you know how can I purchase latest QCAT license? I have tried emailing them but that did not work.

**Comment by peremen** [comment]
Cherry-picked PR #38, closing.
