### ISSUE TITLE
Android 10 dump parsing

### ISSUE THREAD

**Issue by bedrankara** [fgsect/scat#34]
Hey,

I've been parsing .qmdl dumps using scat with my Xiaomi Mi A3 on Android 9 and it worked fine.
I just upgraded the device to Android 10 and scat can not process the dumps anymore (PCAPs are empty, no RRC etc. is being processed). 
I compared the hex dumps of both versions and it seems like parcels returned by the DIAG interface changed with the new Android version. I can provide dumps if needed.

Do you guys have any updates on scat working on Android 10 devices ?

**Comment by peremen** [comment]
Let me check with my POCO F1 also running Android 10. Usually it is related to the baseband firmware (updated along with Android).

**Comment by bedrankara** [comment]
That would help, thanks in advance.

**Comment by peremen** [comment]
Hmm, it looks fine on my environment. I obtained QMDL files using CIT -> Additional Tools (in Hamburger menu) -> MODEM test tools -> Open/Close Offline Log on POCO F1, and RRC messages seems fine on Android 10. Could you please send me a generated QMDL file and/or log message?

**Comment by peremen** [comment]
Closing as stale and possible to parse even later version.
