### ISSUE TITLE
Pixel Support

### ISSUE THREAD

**Issue by peaceforall** [fgsect/scat#37]
Hello,

On your README it says:
>Not working for Pixel devices!

What's blocking this? I have access to Pixel 2 and Pixel 3A and can spend some development time to get this working if you can guide me in the right direction.

**Comment by bedrankara** [comment]
The main issue I have experienced (and appearently many others aswell) with the Pixel devices is they do not easily expose the DIAG port. It seems like some managed to unlock it with custom roms etc. I assume this is also the issue here.

**Comment by peremen** [comment]
> The main issue I have experienced (and appearently many others aswell) with the Pixel devices is they do not easily expose the DIAG port. It seems like some managed to unlock it with custom roms etc. I assume this is also the issue here.

Right. I managed to get DIAG port exposed to USB on my Pixel 2, but just lazy to update README.md and the method itself is really volatile so I didn't wrote about that. As far as I remember, every Pixel series just make it hard to expose DIAG via USB.
