### ISSUE TITLE
Running this tool in Windows

### ISSUE THREAD

**Issue by andrewmmaman** [fgsect/scat#4]
Hello

How can you find the interface ID in Windows?

I'm using ```devcon.exe hwids =usb``` in order to list the devices, but I'm not sure which one to look for.

Can you help me?

**Comment by andrewmmaman** [comment]
It looks like that by using COM19 exposed as ```Samsung Mobile USB Serial Port``` it's possible to start the utility, but I don't get any packets so I'm doing something wrong.

What is the right usage to find the right option? 

What is the difference between ```-s``` (i know it's serial) and ```-a``` (USB), do you mean physical Serial interface or something else?

**Comment by andrewmmaman** [comment]
Can you clarify what you mean by usb? I'm testing this on a Samsung S8 on Windows and I only see one Serial Port exposed by Samsung

**Comment by andrewmmaman** [comment]
I took your advice and used it on Linux, it worked! 
However, either I get the following message:

```
Unknown subcommand 00 for command 0x21
```
Or no output at all, do you have any hints?

**Comment by peremen** [comment]
Could you see the any packets going to UDP port 4729 from Wireshark? No output at all is fine, when things are done correctly.
