### ISSUE TITLE
S8 control plane unavailable

### ISSUE THREAD

**Issue by m-githubnb** [fgsect/scat#44]
Dear guys,
Thank you very much for your tool!
I have tried your tool, and seems everything works fine with my S8 phone (unrooted). I am able to capture and view all user plane packets (UDP) on port 47290. However, there's no sign of control plane packets (port 4729) in Wireshark!
Could you please provide me a solution?

**Comment by peremen** [comment]
Possibly related to #27.

**Comment by peremen** [comment]
See the last comment of #27.
