### ISSUE TITLE
G960F not generating pcap file

### ISSUE THREAD

**Issue by xgongluo** [fgsect/scat#47]
I choose one entry contains DM in *#0808#, and try to capture the message in pcap file

scat.py -t sec -m e333 -u -i 2 -F test_960F.pcap

then try some offline/online operation on phone. then stop the scat.

But the resulting pcap file is always 24 bytes. no LTE message is captured.

My phone firmware is G960FXXU6CSG8, baseband version G960FXXU6CSG4

Is it because the modem is locked?

Can I flash a different firmware to get the LTE message output?

And another question when I read below code:

    def init_diag_e333(self):
        self.io_device.write(b'\x7f\x12\x00\x00\x0f\x00\x00\x00\xa0\x00\x90\x00\x00\x00\x00\xdc\x05\xdc\x05\x7e')
        self.io_device.write(b'\x7f\x12\x00\x00\x0f\x00\x00\x00\xa0\x00\x00\x00\x00\x00\x00AAAA\x7e')

There is a 'AAAA' string, is this correct? why other string are just hex string?

**Comment by peremen** [comment]
Yes, that bytes did worked and am not sure whether changing that will make difference. I am aware of this issue, but have no clue on the solution this moment.

**Comment by peremen** [comment]
See the last comment of #27.
