### ISSUE TITLE
Scat in Galaxy S7, Exynos 8890 chipset

### ISSUE THREAD

**Issue by p3ngdump** [fgsect/scat#49]
Thanks for your hard work!
scat is a great tool.

I have one question.
Currently, i am testing scat on Galaxy S7, Exynos 8890 chipset.
( command: python scat.py -t sec -m e333 -s COM11 -i 1,2,3,4 )

However, only the diag log( stop_diag, init_diag, run_diag ) is displayed, but the messages from the RRC and NAS layers are not displayed.

Galaxy S7, Exynos 8890 are not supported?

Thanks!

**Comment by Cainor** [comment]
I have a Samsung S10+ Exynos version. My command:
```
python3 scat.py -t sec -m e303 -u -a 002:019 -i 2

... Snap ...
       bInterval        :    0x0
      ENDPOINT 0x84: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x84 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
2022-03-01 02:31:06,528 scat.samsungparser (stop_diag) INFO: Stopping diag
2022-03-01 02:31:06,531 scat.samsungparser (init_diag) INFO: Initialize diag
2022-03-01 02:31:06,598 scat.samsungparser (run_diag) INFO: Starting diag

```

And that is it. No capture.

**Comment by peremen** [comment]
I am aware of this issue, but I couldn't understand why it is not working.

**Comment by peremen** [comment]
See the last comment of #27.
