### ISSUE TITLE
Running on Samsung Galaxy S8 Plus

### ISSUE THREAD

**Issue by SuperSadGuy** [fgsect/scat#5]
When I run the tool it shows 
2019-03-18 12:24:12,439 scat.samsungparser (stop_diag) INFO: Stopping diag
2019-03-18 12:24:12,440 scat.samsungparser (init_diag) INFO: Initialize diag
2019-03-18 12:24:12,452 scat.samsungparser (run_diag) INFO: Starting diag
However, when I listen to udp port 47290 and 4729 on Wireshark I do not get anything. 
Please help me!

**Comment by peremen** [comment]
Sorry for delayed response, as our test S8 is not available atm. Did you changed the USB configuration to DM + MODEM + ADB or such? Also have you tried using different interfaces (-i option)?

**Comment by HandyMenny** [comment]
I can tell you that on Samsung SM-G960F, SM-G965F, SM-N960F, SM-G975F and SM-A505F works. Sometimes it stops recording information if SIMs are exchanged or if two SIMs are active. 
The biggest problem I've noticed is that the ARFCN is missing in the GSMTAP header.

**Comment by peremen** [comment]
See the last comment of #27.
