### ISSUE TITLE
LTE Events Parsing and saving into DLF file 

### ISSUE THREAD

**Issue by sbheem** [fgsect/scat#53]
I am able to parse LTE Events but i need info how to save it into dlf file and open with QCAT. 
whatever packet is received from comport is getting parsed and understand which event is triggered but unable to save it into dlf file.
please check and do needful.

Example:
EVENT_LTE_RRC_TIMER_STATUS (ID=1605)  Payload = 0x0D E8 03 00 00 00 00 00 00 00 
		Payload String = Timer Name = Deadlock, Timer Value = 1000, Timer State = Start

	Length:  35
	Header:  23 00 FB 1F 7F 17 04 09 CE 22 F7 00 
	Payload: 15 00 45 66 7F 17 04 09 CE 22 F7 00 
	         0A 0D E8 03 00 00 00 00 00 00 00

**Comment by peremen** [comment]
Save to DLF is not planned. Please use QMDL instead if possible.
