### ISSUE TITLE
(Question) libosmocore 0.12 or higher 

### ISSUE THREAD

**Issue by alphafox02** [fgsect/scat#57]
The project pages mentions libosmocore 0.11.0, just wondered if any testing against 20.04’s packaged libosmocore has been done. Any noticed compatibility-issues with using libosmocore 0.12.0?

**Comment by peremen** [comment]
No, there is no direct dependency on libosmocore on the SCAT's code, only the definitions of GSMTAP included in the libosmocore is used. There is no compatibility issues for any further libosmocore revisions, as long as the GSMTAP structure definition had been changed.
