### ISSUE TITLE
Support for new Exynos series

### ISSUE THREAD

**Issue by iman432** [fgsect/scat#60]
Hi all,

There is any plan for adding support for new Exynos series(phones like Galaxy S21,S22)? I saw in #27 there is no any signaling for 5G Exynos (also i cant get by S21) but we can get signaling by Shannon DM(even old version) so i think should be a way for scat too, thanks.

**Comment by peremen** [comment]
Although I have Exynos derivative (Pixel 6) atm, but I couldn't give any estimations yet. It is a matter of enabling/disabling diag output though.

**Comment by jstys** [comment]
I've had some success getting the Pixel 6 to start logging after digging through its init.rc scripts.

```
#!/bin/bash

function adbsu {
    adb wait-for-device
    adb shell su -c "$1"
}

adbsu "resetprop ro.bootmode usbradio"
adbsu "resetprop ro.build.type userdebug"
adbsu "setprop sys.usb.config acm,dm,adb"
adbsu "persist.vendor.usb.usbradio.config dm"
adbsu "start modem_logging_stop"
adbsu "stop DM-daemon"
adbsu "start DM-daemon"
adbsu "start modem_logging_start"
```

**Comment by iman432** [comment]
> I've had some success getting the Pixel 6 to start logging after digging through its init.rc scripts.
> 
> ```
> #!/bin/bash
> 
> function adbsu {
>     adb wait-for-device
>     adb shell su -c "$1"
> }
> 
> adbsu "resetprop ro.bootmode usbradio"
> adbsu "resetprop ro.build.type userdebug"
> adbsu "setprop sys.usb.config acm,dm,adb"
> adbsu "persist.vendor.usb.usbradio.config dm"
> adbsu "start modem_logging_stop"
> adbsu "stop DM-daemon"
> adbsu "start DM-daemon"
> adbsu "start modem_logging_start"
> ```

But it needs root for modifying init.rc, I guess there is a way without root as Shannon DM is working with new Samsung phones without root or modifying any files on OS.

**Comment by jstys** [comment]
Yes that is true, this method requires a rooted Pixel 6 with Magisk (for `resetprop`).  It doesn't involve modifying init.rc, those were just used as reference to figure out which props needed to be set.
