### ISSUE TITLE
diag1xlogparser parse IP is ignoring timestamps

### ISSUE THREAD

**Issue by HandyMenny** [fgsect/scat#71]
The `parse_ip` function returns a parser_result without `ts` field:
https://github.com/fgsect/scat/blob/4ebb656d09d4409555a19c64e1922f4ab559d04c/parsers/qualcomm/diag1xlogparser.py#L47
https://github.com/fgsect/scat/blob/4ebb656d09d4409555a19c64e1922f4ab559d04c/parsers/qualcomm/diag1xlogparser.py#L60

Even if it's present in pkt_header and it's correctly parsed in parse_diag_log: https://github.com/fgsect/scat/blob/4ebb656d09d4409555a19c64e1922f4ab559d04c/parsers/qualcomm/qualcommparser.py#L378

Furthermore, this will cause pcapwriter to throw an exception because it will call the timestamp method on None:
https://github.com/fgsect/scat/blob/4ebb656d09d4409555a19c64e1922f4ab559d04c/parsers/qualcomm/qualcommparser.py#L341-L358
https://github.com/fgsect/scat/blob/4ebb656d09d4409555a19c64e1922f4ab559d04c/writers/pcapwriter.py#L69-L70
https://github.com/fgsect/scat/blob/4ebb656d09d4409555a19c64e1922f4ab559d04c/writers/pcapwriter.py#L29-L31

**Comment by peremen** [comment]
Closed with fix.
