### ISSUE TITLE
Support for .qmdl2

### ISSUE THREAD

**Issue by Lwao** [fgsect/scat#78]
When trying to analyze a .qmdl2 dump the parse_diag issues a warning of a CRC mismatch.

Are there any plans to add .qmdl2 support for SCAT?

**Comment by peremen** [comment]
The .qmdl2 files which I have collected was basically the same as .qmdl, hence there is no additional code for .qmdl2. Unless someone helps me out, I have no access to look into the .qmdl2 file which is different from .qmdl.

**Comment by HandyMenny** [comment]
@Lwao Do you see files with .bin or .qdss extension in the same folder? If yes unfortunately those aren't Qualcom diag logs, but QDSS logs

**Comment by Lwao** [comment]
The .qmdl2 that I tested contain ADSP data. Could they be considered QDSS logs?

**Comment by peremen** [comment]
I don't think ADSP data is what SCAT is meant to parse, as they are not directly related to the cellular network control plane. Please correct me if I am wrong.

See also: https://infocon.org/cons/DEF%20CON/DEF%20CON%2028/DEF%20CON%20Safe%20Mode%20presentations/DEF%20CON%20Safe%20Mode%20-%20Slava%20Makkaveev%20-%20Pwn2Own%20Qualcomm%20compute%20DSP%20for%20fun%20and%20profit.pdf

**Comment by Lwao** [comment]
I guess that clarifies everything. Thanks for the response.
