### ISSUE TITLE
RC76 --smgs flag error in decode to utf-8

### ISSUE THREAD

**Issue by elkanamol** [fgsect/scat#81]
when I decoding with release 1.1.0 qmdl log file of Sierra Wireless RC7620 from qmdl file to pcap file, the script is crash with massage below. 
with flags:
`scat -t qc -d rc7620.qmdl -F rc7620.pcap --events --msgs`

the crash/tracing:
```Traceback (most recent call last):
  File "/home/jade/.local/bin/scat", line 8, in <module>
    sys.exit(scat_main())
  File "/home/jade/Downloads/scat-1.1.0/src/scat/main.py", line 193, in scat_main
    current_parser.read_dump()
  File "/home/jade/Downloads/scat-1.1.0/src/scat/parsers/qualcomm/qualcommparser.py", line 413, in read_dump
    self.run_diag()
  File "/home/jade/Downloads/scat-1.1.0/src/scat/parsers/qualcomm/qualcommparser.py", line 326, in run_diag
    parse_result = self.parse_diag(pkt)
  File "/home/jade/Downloads/scat-1.1.0/src/scat/parsers/qualcomm/qualcommparser.py", line 284, in parse_diag
    return self.parse_diag_ext_msg(pkt)
  File "/home/jade/Downloads/scat-1.1.0/src/scat/parsers/qualcomm/qualcommparser.py", line 510, in parse_diag_ext_msg
    log_content = pkt_body[0].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 22: invalid start byte
```
when doing without --msgs its not crashed, but still I got many WORNING massages:

`scat.qualcommparser (parse_lte_ml1_scell_meas_response) WARNING: Unknown LTE ML1 Serving Cell Meas Serving Cell Measurement Result subpacket version 18
`

**Comment by peremen** [comment]
For the first part, I haven't seen the same type of error before. Please try with latin-1 instead of utf-8. If that doesn't solve the problem, please send the qmdl file (only the relevant portion is enough) in encrypted form, to the address in my profile. Here is my GPG key: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5bccd9e11596004bfd69b3db15f1dd7e409e252b

For the second warning, they are related to the measurements. However, no messages will be printed so you can ignore it.

**Comment by elkanamol** [comment]
Hi @peremen, 
did you mean to change the source code per traceback code line     `log_content = pkt_body[0].decode('utf-8')` to  `log_content = pkt_body[0].decode('cp1252')`?

I will send you example qmdl file to check it also.

**Comment by elkanamol** [comment]
Thanks, it seems like solve the issue, I just downland the latest source code and rebuild it by `pip install -e .`, note that the pyproject.toml still set as release 1.0.0 and also the build.
now when I running same file and command it working well and I don't got traceback crashing.
