### ISSUE TITLE
scat exited with error " TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by sramar** [fgsect/scat#83]
**Branch : v1.1.0**

Mobile : Vivo , Qualcomm based 

Executed command scat -t qc -u -a 003:018 -i 2.    003:018 -> belongs to diag ports .  After "Initializing diag" print getting below error. Can you please help 

![image](https://github.com/fgsect/scat/assets/36079840/fb1cc172-5ca2-4144-a6fa-4d148df25ec3)

**Comment by peremen** [comment]
It seems that the DIAG port is not working as intended, because before entering that part the app will print the version information from the baseband. From the log output I can't see version and build information. Are you sure that the DIAG port is working?

**Comment by sramar** [comment]
Yes. Diag port is working when i'm using using QXDM on windows machine. Please find the dmesg output after connecting mobile 

![image](https://github.com/fgsect/scat/assets/36079840/abbbb840-5b72-4937-80f4-12a1b5398826)
![image](https://github.com/fgsect/scat/assets/36079840/f3902a6b-f826-4705-b4d5-3995b38f2916)

**Comment by peremen** [comment]
I'm sorry, in this case I have no idea. cdc-wdm0 is not used by SCAT at all.
