### ISSUE TITLE
Add support for whole 0xb826 and 0xb0cd output to txt

### ISSUE THREAD

**Issue by 1alessandro1** [fgsect/scat#84]
Hello, this tool is very useful to extract Qualcomm modem's capabilities (LTE, EN-DC, and SA) from DIAG logs, it would be very useful to convert the output from the command 

`python3 scat.py -t qc -d "test_0620_1317_1.dlf" -F test.pcap` 

to extract hexdumps of 0xB826 and 0xB0CD messages into a single CSV file

We discussed this topic with @HandyMenny, could it be possible to create a parameter to collect all the distinct 0xb826 messages (since for every 100 combos there is a new hexdump) and parse the whole output to a txt file?

For example:
```
# For 0xB0CD (LTE capabilities)
python3 scat.py -t qc -d "test_0620_1317_1.dlf" --extract-0xb0cd-to-txt output.txt

# For 0xB826 (EN-DC capabilities)
python3 scat.py -t qc -d "test_0620_1317_1.dlf" --extract-0xb826-to-txt output.txt
```
It would be very useful since usually it is difficult to extract the full Hardware combos from UEs such as routers and phones.

**Comment by peremen** [comment]
I added an option to print CA combos (`--cacombos`) in the current master, which will be included in the next release. Unlike previous revisions, this will output everything in one line so user can easily grep the needed output.

Please suggest any postprocessing procedure if it can make the output more useful to the users, as I have never touched the data before.

**Comment by HandyMenny** [comment]
@peremen When I was asked how to better integrate scat with my uecapabilityparser, I thought that maybe a command could be added to scat to tell it which messages to filter/ignore (based on ids like 0xB0CD etc..) or which messages to export a hexdump of for debugging.
But these are far more invasive and complex changes; the output of the new option, on the other hand, is simple and perfect. Thanks :)
