### ISSUE TITLE
LTE identify TDD

### ISSUE THREAD

**Issue by grmono** [fgsect/scat#86]
I checked through the Qualcomm LTE parser and it seems the FDD flag is hardcoded in the code, is it possible to identify somehow from the Qualcomm diag port data that the cell is tdd or fdd?

**Comment by peremen** [comment]
>  it seems the FDD flag is hardcoded in the code

This is only for generating RAR in the `parse_lte_mac_rach_response` for a convenience's sake, and not related to any kind of identification. Check the serving cell information/band and whether the current EARFCN/band is one of the TDD bands.
