### ISSUE TITLE
SIP packets on scat capture

### ISSUE THREAD

**Issue by agrigoreat** [fgsect/scat#88]
Hi everyone.
I am capturing on a EG25 Quectel device which has a VoLTE SIM card inside but the capture(in wireshark) displays the SIP packages as UDP instead of SIP. Is there a way i can do to see SIP packages instead of UDP?  
![image](https://github.com/fgsect/scat/assets/113265876/7c74a301-8553-4998-a122-cc284fc34ebe)

**Comment by peremen** [comment]
Hi, please decode UDP port 47290 as IP. A fictional IP/UDP header is attached before the SIP packet.

**Comment by mohanrajpExploring** [comment]
@agrigoreat 

I'm using `lte_rrc || nas-eps || sip` as the filter for .pcap logs, you can see sip logs are visible directly.
![Screenshot from 2024-05-02 21-54-31](https://github.com/fgsect/scat/assets/168116222/aec70349-84da-44c9-8ae5-d331af162aa3)
---

**Comment by arifkyi** [comment]
Hello ,

Need your kindly help,

I already decoded  with SIP with temporary and permanently set in Preferences -> Protocol -> SIP
but yield no successfull decoded:

Kindly see below snapshot:

<img width="1659" alt="Screen Shot 2024-12-08 at 17 00 57" src="https://github.com/user-attachments/assets/c5135f16-7dfd-4562-a2e0-7bc846cb32f8">
<img width="1339" alt="Screen Shot 2024-12-08 at 17 01 18" src="https://github.com/user-attachments/assets/d81cce21-5264-455e-9699-9cce6af9e28d">

Thank you very much in advance
