### ISSUE TITLE
Unhandled LTE RRC packet version 16

### ISSUE THREAD

**Issue by HandyMenny** [fgsect/scat#9]
I was analyzing some baseband dumps of Xiaomi phones and I encountered this error. I solved it by adding 16 next to 15 here: https://github.com/fgsect/scat/blob/c637d055ce6b634aa6e6b9e2d2699752bdd465eb/parsers/qualcommparser.py#L1649 
However I don't know if it's the right way

**Comment by peremen** [comment]
For LTE RRC diag items, Qualcomm slightly changes the channel definition of LTE RRC messages between versions (that's the reason of that if statement). Currently the values are collected from my set of devices, so there might be some missing version numbers. I will check whether the revision had changed channel definition, and could fix it then.

**Comment by HandyMenny** [comment]
This should be helpful: 

2019-04-26 21:54:59,472 scat.qualcommparser (parse_lte_rrc) WARNING: Multi radio packet, unknown_1 = 1, subscription_id = 0
2019-04-26 21:54:59,379 scat.qualcommparser (parse_diag_multisim) DEBUG: Hexdump: 
98 01 00 00 00 00 00 00 99 02 13 00 00 a0 44 ed	..............D.
27 08 e7 00 6f 98 02 00 c4 c8 00 00 00         	'...o........
-------- end --------
2019-04-26 21:54:59,472 scat.qualcommparser (parse_lte_rrc) WARNING: Unhandled LTE RRC packet version 16
2019-04-26 21:54:59,472 scat.qualcommparser (parse_lte_rrc) DEBUG: Hexdump: 
10 0d 22 00 9b 01 3a 07 00 00 19 04 05 00 00 00	.."...:.........
00 07 00 40 03 0e 43 e0 51 30                  	...@..C.Q0
-------- end --------

**Comment by HandyMenny** [comment]
I have found another:  "Unhandled LTE RRC packet version 22". In this case I used the channel definition of "# RRC Packet v13-v14", it seems to work pretty well

**Comment by peremen** [comment]
Okay, could you please check the "qc-lte-rrc-versions" branch? If it works for your case, then I will close this issue.

**Comment by HandyMenny** [comment]
Thank you for your work. The commit https://github.com/fgsect/scat/commit/06c2ee32fa07cf8a32eb41da08bcfd0f87bde0ec is ok
