### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by TrusterBSW** [fgsect/scat#91]
Hello,
I'm looking to install scat, but I have some errors I don't understand 

When i try to install it with pip directly from git
`$ pip install https://github.com/fgsect/scat`
`Collecting https://github.com/fgsect/scat`
`  Downloading https://github.com/fgsect/scat`
`     / 286kB 4.5MB/s`
`  Cannot unpack file /tmp/pip-unpack-bj9Uqn/scat (downloaded from /tmp/pip-req-build-E3kXLz, content-type: text/html; charset=utf-8); cannot detect archive format`
`Cannot determine archive format of /tmp/pip-req-build-E3kXLz`

and when i use the other installation methode given in the README, it says that there is no setup.py found
`~/scat$ pip install -e .`
`Directory '.' is not installable. File 'setup.py' not found.`

how can I install it ?

**Comment by peremen** [comment]
What is the output of your `pip --version`?

**Comment by TrusterBSW** [comment]
I tried with both pip and pip3

`pip --version`
`pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)`

`pip3 --version`
`pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)`

**Comment by HandyMenny** [comment]
The correct command is `pip install git+https://github.com/fgsect/scat`, otherwise pip downloads the web page

**Comment by peremen** [comment]
Thanks, I will update the README. As the name `scat` is taken in the pip, I will name the application something else for the pip.

**Comment by TrusterBSW** [comment]
> 1. SCAT does not support Python 2.x.
> 
>     2. Python 3.7 should work, could you please try with the latest pip version? 18.1 seems be a bit old.

You were right, I just installer a debian 11 with pip 20.3.4 and python 3.9, now it works.
