### ISSUE TITLE
Parse_lte_ml1_scell_meas_response / 

### ISSUE THREAD

**Issue by POPTEST1234** [fgsect/scat#94]
scat.qualcommparser (parse_lte_ml1_scell_meas_response) WARNING: Unknown LTE ML1 Serving Cell Meas Serving Cell Measurement Result subpacket version 26

Hi, I have tried to use scat to convert OPPO log to pcap. However the convert process cannot be finish property due errorparse_lte_ml1_scell_meas_response

Dear devs, how can we deal with it?

**Comment by peremen** [comment]
That's for cell measurement, which will not be included in the PCAP unless you specified `--combine-stdout`. You can skip if you only want RRC/NAS.
